# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='', max_length=64),
        ),
    ]
