# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prompt',
            old_name='q_type',
            new_name='category',
        ),
    ]
