# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170930_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='category',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='override_html',
            field=models.TextField(default=None, null=True),
        ),
    ]
