# Generated by Django 5.2.14 on 2026-05-17 21:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_prompt_entry_timestamps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['author', '-pub_date'], name='core_entry_author__d99711_idx'),
        ),
    ]
