# Generated by Django 5.2.14 on 2026-05-17 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_promptsend'),
        ('core', '0006_entry_core_entry_author__d99711_idx'),
    ]

    operations = [
    ]
