# Generated by Django 5.2.14 on 2026-05-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_seed_thirty_days_of_prompts'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='archived_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
