# Generated by Django 5.2.14 on 2026-05-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_unsubscribe_new_users_by_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pending_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
