# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 17:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('mail_day', models.DateTimeField()),
                ('override_html', models.TextField(default=None)),
                ('q_type', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='prompt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Prompt'),
        ),
    ]
