# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('mail_day', models.DateTimeField()),
                ('override_html', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='prompt',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='core.Prompt'),
        ),
    ]
