# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170930_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='override_html',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
